language: go
go:
  - 1.6.2
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
install:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
